version: '3.8'

# Ortak ayarları tanımlıyoruz
x-common-environment: &common-env
  MYSQL_ROOT_PASSWORD: root_password
  MYSQL_USER: repl_user
  MYSQL_PASSWORD: repl_pass123
  TZ: Europe/Istanbul

x-common-healthcheck: &common-healthcheck
  test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot_password"]
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s

x-master-volumes: &master-volumes
  - "/etc/timezone:/etc/timezone:ro"
  - "/etc/localtime:/etc/localtime:ro"
  # Config dosyalarını yükleyelim
  - "./my.cnf:/etc/mysql/my.cnf:ro"
  - "./1_network.cnf:/etc/mysql/conf.d/1_network.cnf:ro"
  - "./2_group_replication.cnf:/etc/mysql/conf.d/2_group_replication.cnf:ro"

x-slave-volumes: &slave-volumes
  - "/etc/timezone:/etc/timezone:ro"
  - "/etc/localtime:/etc/localtime:ro"
  # Config dosyalarını yükleyelim
  - "./my.cnf:/etc/mysql/my.cnf:ro"
  - "./1_network.cnf:/etc/mysql/conf.d/1_network.cnf:ro"
  - ./slave.cnf:/etc/mysql/conf.d/slave.cnf:ro
  
x-base-master: &mysql-base-master
  image: mysql:5.7
  restart: always
  environment:
    <<: *common-env
  healthcheck:
    <<: *common-healthcheck
  volumes: *master-volumes

x-base-slave: &mysql-base-slave
  image: mysql:5.7
  restart: always
  environment:
    <<: *common-env
  healthcheck:
    <<: *common-healthcheck
  volumes: *slave-volumes

services:
  master1:
    <<: *mysql-base-master
    container_name: master1
    hostname: master1
    command: >
      --defaults-file=/etc/mysql/my.cnf
      --server-id=1
      --group_replication_local_address="master1:24901"

  master2:
    <<: *mysql-base-master
    container_name: master2
    hostname: master2
    depends_on:
      master1:
        condition: service_healthy
    command: >
      --defaults-file=/etc/mysql/my.cnf
      --server-id=2
      --group_replication_local_address="master2:24902"

  master3:
    <<: *mysql-base-master
    container_name: master3
    hostname: master3
    depends_on:
      master2:
        condition: service_healthy
    command: >
      --defaults-file=/etc/mysql/my.cnf
      --server-id=3
      --group_replication_local_address="master3:24903"

  slave:
    <<: *mysql-base-slave
    container_name: slave
    hostname: slave
    depends_on:
      master3:
        condition: service_healthy
    command: >
      --defaults-file=/etc/mysql/my.cnf
      --server-id=4

# # Persisted volumes
# volumes:
#   master1_data:
#   master2_data:
#   master3_data:
#   slave_data: