SET SQL_LOG_BIN=0;

STOP SLAVE;
RESET SLAVE;

CHANGE MASTER TO 
MASTER_HOST='mysql-master',
MASTER_PORT=3306,
MASTER_USER='rep_user',
MASTER_PASSWORD='YourStrongPassword';

START SLAVE;

SHOW SLAVE STATUS\G

SET SQL_LOG_BIN=1;



-- STOP SLAVE;
-- RESET SLAVE;
-- CHANGE MASTER TO
--   MASTER_HOST='mysql-master',
--   MASTER_USER='rep_user',
--   MASTER_PASSWORD='rep_pass123',
--   MASTER_LOG_FILE='mysql-bin.000001',
--   MASTER_LOG_POS=107;
-- START SLAVE;


-- SHOW SLAVE STATUS\G

-- SET SQL_LOG_BIN=1;