services:
  node1:
    image: mysql:5.7
    container_name: gr-node1
    hostname: node1
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog_checksum=NONE
      --enforce-gtid-consistency=ON
      --gtid_mode=ON
      --master_info_repository=TABLE
      --relay_log_info_repository=TABLE
      --transaction_write_set_extraction=XXHASH64
      --log_slave_updates=ON
      --plugin-load=group_replication.so
      --group_replication_local_address=node1:33061
      --group_replication_group_seeds=node1:33061,node2:33061,node3:33061
      --group_replication_bootstrap_group=OFF
      --group_replication_single_primary_mode=ON
      --group_replication_enforce_update_everywhere_checks=OFF
      --group_replication_start_on_boot=OFF
    volumes:
      - node1_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro
      - ./1_network.cnf:/etc/mysql/conf.d/1_network.cnf:ro
      - ./2_group_replication.cnf:/etc/mysql/conf.d/2_group_replication.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Europe/Istanbul
    ports:
      - "3307:3306"    # MySQL port
      - "33061:33061"  # Group Replication port
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  node2:
    image: mysql:5.7
    container_name: gr-node2
    hostname: node2
    command: >
      --server-id=2
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog_checksum=NONE
      --enforce-gtid-consistency=ON
      --gtid_mode=ON
      --master_info_repository=TABLE
      --relay_log_info_repository=TABLE
      --transaction_write_set_extraction=XXHASH64
      --log_slave_updates=ON
      --plugin-load=group_replication.so
      --group_replication_local_address=node2:33061
      --group_replication_group_seeds=node1:33061,node2:33061,node3:33061
      --group_replication_bootstrap_group=OFF
      --group_replication_single_primary_mode=ON
      --group_replication_enforce_update_everywhere_checks=OFF
      --group_replication_start_on_boot=OFF
    volumes:
      - node2_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro
      - ./1_network.cnf:/etc/mysql/conf.d/1_network.cnf:ro
      - ./2_group_replication.cnf:/etc/mysql/conf.d/2_group_replication.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Europe/Istanbul
    ports:
      - "3308:3306"
      - "33062:33061"
    networks:
      - mysql_network
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  node3:
    image: mysql:5.7
    container_name: gr-node3
    hostname: node3
    command: >
      --server-id=3
      --log-bin=mysql-bin
      --binlog-format=ROW
      --binlog_checksum=NONE
      --enforce-gtid-consistency=ON
      --gtid_mode=ON
      --master_info_repository=TABLE
      --relay_log_info_repository=TABLE
      --transaction_write_set_extraction=XXHASH64
      --log_slave_updates=ON
      --plugin-load=group_replication.so
      --group_replication_local_address=node3:33061
      --group_replication_group_seeds=node1:33061,node2:33061,node3:33061
      --group_replication_bootstrap_group=OFF
      --group_replication_single_primary_mode=ON
      --group_replication_enforce_update_everywhere_checks=OFF
      --group_replication_start_on_boot=OFF
    volumes:
      - node3_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro
      - ./1_network.cnf:/etc/mysql/conf.d/1_network.cnf:ro
      - ./2_group_replication.cnf:/etc/mysql/conf.d/2_group_replication.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Europe/Istanbul
    ports:
      - "3309:3306"
      - "33063:33061"
    networks:
      - mysql_network
    depends_on:
      node2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5

  setup:
    image: mysql:5.7
    container_name: gr-setup
    hostname: setup
    restart: "no"
    entrypoint: /run.sh
    volumes:
      - ./run.sh:/run.sh
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      node3:
        condition: service_healthy
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge

volumes:
  node1_data:
  node2_data:
  node3_data:
