# Önce mysql master servisini başlat
# - monitor_user ve monitor_password ile monitor kullanıcısı oluşturuyoruz.
# - proxysql

# ve ardından mysql slave servislerini oluşturuyoruz.
# Sonra proxysql ve phpmyadmin servislerini oluşturuyoruz.

services:
  test:
    image: mysql:5.7
    container_name: test
    restart: always
    command: >
      --defaults-file=/etc/mysql/my.cnf
      --server-id=1
      --group_replication_ip_whitelist="0.0.0.0/0"
      --group_replication_start_on_boot=OFF
      --group_replication_local_address="test:24901"
      --port=3310
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - ./ag.cnf:/etc/mysql/conf.d/ag.cnf
      - ./group_replication.cnf:/etc/mysql/conf.d/group_replication.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      # MYSQL_PWD: root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 5
